name: oura
version: 0.0.1
description: https://cloud.ouraring.com
homepage: https://github.com/jpnurmi/oura.dart

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  http: ^0.13.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
